Added task 2 homework 6 and tests for task 2 homework 6.
Diana-Govorova/SPbSU-SemesterII pull request #10
Opened 2020-05-25 14:18 UTC by Diana-Govorova

2020-06-09 15:51 UTC, yurii-litvinov requested changes

2020-06-09 15:51 UTC, yurii-litvinov commented on HW6/TestsForTask2/TestsForTask2.cs
> +            using (StreamWriter sw = new StreamWriter("test.txt"))
var

2020-06-09 15:51 UTC, yurii-litvinov commented on HW6/task2/CursorController.cs
> +    class CursorController
А надо комментарии и к классам тоже

2020-06-09 15:51 UTC, yurii-litvinov commented on HW6/task2/CursorController.cs
> +            Console.Clear();
Не, так нельзя, адово мерцать будет. Тут надо SetCursorPosuition использовать.

2020-06-09 15:51 UTC, yurii-litvinov commented on HW6/task2/CursorController.cs
> +        }
И как-то копипаст :)

2020-06-09 15:51 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +        public int Rows { get; }
Мм, это поле и свойство, хоть и называются одинаково, формально никак не связаны

2020-06-09 15:51 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +            StreamReader reader = new StreamReader(path);
using var

2020-09-02 12:50 UTC, yurii-litvinov requested changes

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/TestsForTask2/TestsForTask2.cs
> +            char[,] mapArrayTest = new char[5, 5] { { '#', '#', '#', '#', '#' }, { '#', ' ', ' ', ' ', '#' }, { '#', ' ', '@', ' ', '#' }, { '#', ' ', ' ', ' ', '#' }, { '#', '#', '#', '#', '#' } };
Это лучше было расположить в двумерном виде,
```charp
new char[5, 5] { 
    { '#', '#', '#', '#', '#' }, 
    { '#', ' ', ' ', ' ', '#' }, 
    { '#', ' ', '@', ' ', '#' }, 
    { '#', ' ', ' ', ' ', '#' }, 
    { '#', '#', '#', '#', '#' } };
```

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/TestsForTask2/TestsForTask2.cs
> +    }
Тесты должны бы ещё проверять, что персонаж через стенки не проходит и не вываливается за границы карты, если там не стенка

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/CursorController.cs
> +        public CursorController(string path, Action <int, int> action)
Пробел лишний, `Action<int, int> action`, это ж просто объявление параметра типа-генерика

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/CursorController.cs
> +		/// <summary>
Беда с отступами, табуляции и пробелы перепутаны

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/CursorController.cs
> +        }
Можно через =>

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/CursorController.cs
> +            this.action = action;
Можно было action-у более говорящее имя дать. А так у Вас даже комментария к параметру  конструктора нет, что сюда передавать?..

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +    /// Class, that defines map.
Тут запятая в английском не ставится

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +		public bool CanGo(int x, int y)
Тоже беда с отступами

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +        public char[,] MapArray { get => mapArray; }
Можно было `public char[,] MapArray { get; private set; }` и  поле mapArray убрать вообще

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +        private int columns;
А они не нужны, MapArray сам помнит свои размеры

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +            var reader = new StreamReader(path);
Вот тут точно using var

2020-09-02 12:50 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +                    j++;
Пробела не хватает, и с отступами беда

2020-10-04 20:36 UTC, Diana-Govorova commented on HW6/task2/Map.cs
> +            var reader = new StreamReader(path);
Программа пишет: Функция находится на этапе разработки и тд
В общем, нельзя так сделать

2020-10-18 12:08 UTC, yurii-litvinov approved these changes
В целом всё ок, зачтена

2020-10-18 12:08 UTC, yurii-litvinov commented on HW6/TestsForTask2/TestsForTask2.cs
> +			//controller.OnRight(null, null);
Закомментированный код не нужен

2020-10-18 12:08 UTC, yurii-litvinov commented on HW6/task2/CursorController.cs
> +		/// <param name="action">Move coordinates.</param>
Весьма загадочный комментарий, особенно если речь идёт о функции. Move to coordinates? Или, может, "Move cursor to coordinates"?

2020-10-18 12:08 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +		public (int x, int y) PlayerPosition { get => playerPosition; set => playerPosition = value; }
Оно могло бы быть автоматическим свойством, геттер и сеттер же не делают ничего содержательного

2020-10-18 12:09 UTC, yurii-litvinov commented on HW6/task2/Map.cs
> +            var reader = new StreamReader(path);
Так Вы пишете под какую-то древнюю версию .NET Core :)

2020-10-19 23:35 UTC, merged