Added homework 7 task 2
Diana-Govorova/SPbSU-SemesterII pull request #13
Opened 2020-06-09 15:22 UTC by Diana-Govorova

2020-06-09 16:30 UTC, yurii-litvinov requested changes

2020-06-09 16:30 UTC, yurii-litvinov commented on HW7/task2/Form1.cs
> +    public partial class Form1 : Form
Form1 --- имя как-то не очень

2020-06-09 16:30 UTC, yurii-litvinov commented on HW7/task2/Form1.cs
> +        Graphics g;
Я надеюсь, это какой-то копипаст из интернета? :)

2020-06-09 17:02 UTC, Diana-Govorova commented on HW7/task2/Form1.cs
> +        Graphics g;
Да, это индус какой-то на ютубе видеоурок показывает

2020-06-09 17:04 UTC, Diana-Govorova commented on HW7/task2/Form1.cs
> +        Graphics g;
Ну по крайней мере я по его уроку делала

2020-06-09 18:41 UTC, yurii-litvinov requested changes

2020-06-09 18:41 UTC, yurii-litvinov commented on HW7/task2/Form1.cs
> +        Graphics g;
Но Вы ж не индус. Приведите в соответствие индустриальным практикам хотя бы. Индусам можно писать "Graphics **Ж**", матмеховцам --- нет

2020-09-16 15:25 UTC, yurii-litvinov requested changes
Надо целую секунду ждать, пока часы нарисуются. Нельзя ли сделать так, чтобы они рисовались сразу?

2020-09-16 15:25 UTC, yurii-litvinov commented on HW7/task2/Clock.cs
> +        private void clockFace()
Методы ж с заглавной именуются

2020-09-16 15:25 UTC, yurii-litvinov commented on HW7/task2/Clock.cs
> +        /// <param name="e"></param>
А пустые тэги с параметрами не нужны

2020-09-16 15:25 UTC, yurii-litvinov commented on HW7/task2/Clock.cs
> +            Coordinate handCoordinate = new Coordinate();
Это вообще можно не делать, а объявлять handCoordinate  в 90-й строчке, когда для неё уже есть значение. Иначе тут просто низачем создаётся new Coordinate()

2020-09-16 15:25 UTC, yurii-litvinov commented on HW7/task2/Clock.cs
> +        }
И тут бы ещё пустую строчку

2020-09-16 15:25 UTC, yurii-litvinov commented on HW7/task2/Clock.cs
> +        private Coordinate hourHandCoordinate(int hourValue, int minuteValue, int handLength)
И тут, с заглавной бы

2020-10-16 14:02 UTC, yurii-litvinov requested changes
Форму можно скукожить до неюзабельного состояния (а не должно быть так), и всё ещё приходится секунду ждать отрисовки стрелок. А в остальном всё почти ок уже, осталось только это поправить

2020-10-16 14:02 UTC, yurii-litvinov commented on HW7/task2/Form1.cs
> +    public partial class  Clock : Form
Теперь два файла с одним и тем же классом, только этот плохой :) Забыли удалить?

2020-11-29 10:42 UTC, yurii-litvinov requested changes
Да, теперь всё отлично, только почистите от ненужного кода, пожалуйста

2020-11-29 10:42 UTC, yurii-litvinov commented on HW7/task2/Form1.cs
> +﻿using System;
Мне кажется, этого файла нет в проекте и он не нужен

2020-11-29 10:42 UTC, yurii-litvinov commented on HW7/task2/Clock.cs
> +//using System.Windows.Forms.VisualStyles;
Закомментированный код не нужен

2020-11-30 08:54 UTC, yurii-litvinov approved these changes
👍

2020-12-01 18:58 UTC, merged