Add task1 homework4 and tests for it.
Diana-Govorova/SPbSU-SemesterII pull request #15
Opened 2020-10-15 20:46 UTC by Diana-Govorova

2020-10-16 14:14 UTC, yurii-litvinov requested changes
Почти всё ок, но код выглядит, будто в него граната попала. Поправьте, пожалуйста

2020-10-16 14:14 UTC, yurii-litvinov commented on HW4/Task1Tests/Task1Tests.cs
> +
Лишняя пустая строчка :)

2020-10-16 14:14 UTC, yurii-litvinov commented on HW4/task1/Number.cs
> +		public double Value { get; set; }
Не уверен, что ему нужен public-сеттер

2020-10-16 14:14 UTC, yurii-litvinov commented on HW4/task1/Operation.cs
> +        public INode Right { get; set; }
Что-то с отступами беда

2020-10-16 14:14 UTC, yurii-litvinov commented on HW4/task1/Substraction.cs
> +	{
И тут

2020-10-16 14:14 UTC, yurii-litvinov commented on HW4/task1/Tree.cs
> +    {
И тут!

2020-10-16 14:14 UTC, yurii-litvinov commented on HW4/task1/Tree.cs
> +		}
Это можно было сделать switch expression-ом, получилось бы втрое короче

2020-10-16 16:38 UTC, Diana-Govorova commented on HW4/task1/Operation.cs
> +        public INode Right { get; set; }
Возможно просто криво отображается из--за того, что у меня где то пробелы, а где то табы

2020-10-16 16:40 UTC, Diana-Govorova commented on HW4/task1/Number.cs
> +		public double Value { get; set; }
Если делать set приватным, то программа не дает установить в тестах значения

2020-10-16 16:46 UTC, Diana-Govorova commented on HW4/task1/Tree.cs
> +		}
Пробовала через switch, visual studio пишет что типо функция в разработке и ее нельзя использовать:(

2020-10-16 17:02 UTC, yurii-litvinov commented on HW4/task1/Operation.cs
> +        public INode Right { get; set; }
Именно так. Но смысл замечания как раз в том, что так быть не должно. Стоит включить отображение пробельных символов (в меню "Edit" -> "Advanced") и везде поправить.

2020-10-16 17:04 UTC, yurii-litvinov commented on HW4/task1/Tree.cs
> +		}
Во-первых, можно хотя бы просто switch. А чтобы был switch expression, надо включить C# 8 в настройках проекта, да.

2020-10-18 12:14 UTC, yurii-litvinov approved these changes
Ну ладно, в основном всё ок, зачтена

2020-10-18 12:14 UTC, yurii-litvinov commented on HW4/task1/Number.cs
> +		public double Value { get; set; }
А надо? Конструктор же есть. Немутабельные объекты всегда лучше мутабельных. Тем более, делать что-то в боевом коде только ради тестов --- портить боевой код

2020-10-19 21:50 UTC, merged