Added 1 task and test for 1 task 2 homework.
Diana-Govorova/SPbSU-SemesterII pull request #3
Opened 2020-04-02 18:00 UTC by Diana-Govorova

2020-04-16 18:22 UTC, yurii-litvinov requested changes

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            public int Value { get => value; set => this.value = value; }
Лучше всё-таки геттеры и сеттеры на отдельных строках писать, так:
```csharp
public int Value
{
    get => value;
    set => this.value = value;
}
```

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                head.Value = value;
И после этого не делаем return, а продолжаем добавлять :)

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            var addedNode = new Node();
А зачем его тут создавать, если он может ещё не понадобиться?

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                return;
Надо как-то дать знать вызывающему, что операция неуспешна (исключением или кодом возврата)

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                addedNode.Value = value;
Я бы Node сделал конструктор, который принимает value

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            var NextNode = head.Next;
Переменые всегда-всегда именуются со строчной

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            if (position == 1)
А если 0?

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1Tests/LinkedListTests.cs
> +        LinkedList linkedList;
private

2020-04-16 18:22 UTC, yurii-litvinov commented on HW2/task1Tests/LinkedListTests.cs
> +            Assert.AreEqual(linkedList.GetNodeValueByPosition(2), 20);
Наоборот, сначала ожидаемый результат, затем реальный. Это влияет на сообщения об ошибках, если тейт не пройдёт

2020-04-16 18:51 UTC, Diana-Govorova commented on HW2/task1Tests/LinkedListTests.cs
> +        LinkedList linkedList;
не дает сделать приватным

я вам в телеграме выслала что оно мне пишет

2020-04-16 18:52 UTC, Diana-Govorova commented on HW2/task1/Linkedlist.cs
> +                addedNode.Value = value;
а это как ?
немного  не поняла

2020-05-04 20:55 UTC, yurii-litvinov requested changes
Надо ещё немного поправить

2020-05-04 20:55 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            }
А вот геттеры-cеттеры по умолчанию пишутся в одну строчку: `public Node Next { get; set; }`

2020-05-04 20:55 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            }
1) Надо пустую строку между свойствами
2) Это тоже могло бы быть автоматическое свойство

2020-05-04 20:55 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                head.Next = temporaryNode;
Ии не делаем return, поэтому всё продолжает выполняться

2020-05-04 20:55 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                return;
Иии size не обновили. Баги, баги повсюду :)

2020-05-04 20:55 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +        /// <param name="position">Index.</param>
А чего возвращает? Не задокументировано :)

2020-05-04 20:55 UTC, yurii-litvinov commented on HW2/task1/Program.cs
> +
Лишняя пустая строчка

2020-05-13 09:53 UTC, yurii-litvinov requested changes

2020-05-13 09:53 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                return;
Ну а так ему пофиг на position, и если список пустой, то Add(-5, 1); нормально отрабатывает, но если не пустой, то та же команда бросает исключение внезапно

2020-05-13 09:53 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            if (position == 1)
Нумерация позиций начинается с 1, нетрадиционно

2020-05-13 09:53 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            for (int i = 0; i < position - 2; i++)
Ну раз уж позиции с единицы, то `for (int i = 1; i < position - 1; i++)`

2020-05-13 09:53 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                nextNode = nextNode.Next;
А если position больше размера списка?

2020-05-13 09:53 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            return true;
А этот метод может когда-нибудь вернуть не true?

2020-05-13 09:53 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            for (int i = 0; i < position - 2; i++)
Опять-таки, что будет, если позиция больше размера списка?

2020-05-13 09:53 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            }
Вообще, что-то это копипаст, я такой точно код третий раз уже вижу

2020-05-31 10:22 UTC, yurii-litvinov requested changes
Ещё немножко критичческих багов осталось, надо дофиксить

2020-05-31 10:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                throw new InvalidOperationException("Invalid position");
А это недостижимый код, потому что мы в самом начале проверили, что position <= size

2020-05-31 10:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            if ((position < 0) || (position > size))
position >= size. В списке же элементы от 0 до size - 1

2020-05-31 10:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            if ((position < 0) || (position > size))
И тут

2020-05-31 10:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            if ((position < 0) || (position > size))
И тут

2020-05-31 10:22 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            }
Надо поправить

2020-05-31 10:22 UTC, yurii-litvinov commented on HW2/task1Tests/LinkedListTests.cs
> +            catch (Exception exeption)
Вы ведь кидаете InvalidOperationException, тут и ловить бы следовало именно его

2020-05-31 12:12 UTC, yurii-litvinov requested changes

2020-05-31 12:12 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            if ((position < 0) || (position > size - 1))
Это же то же самое, что position >= size :)

2020-05-31 12:12 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            for (int i = 0; i <= position - 1; i++)
А это --- i < position :)

2020-05-31 12:12 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                    throw new IndexOutOfRangeException();
А этого по идее быть не должно, мы ведь проверили position

2020-05-31 12:12 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +                throw new ArgumentException("There's no element with input position.");
Избыточно, следующий if это поймает

2020-05-31 12:12 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            }
Проход по списку до заданной позиции так в отдельный метод и не вынесли, а надо, копипаст же. А копипаст суть ересь.

2020-05-31 12:21 UTC, Diana-Govorova commented on HW2/task1/Linkedlist.cs
> +            }
aa, я просто не совсем поняла что нужно сделать

2020-05-31 12:21 UTC, Diana-Govorova commented on HW2/task1/Linkedlist.cs
> +            if ((position < 0) || (position > size - 1))
аааа, эти ошибки когда-нибудь кончатся.......:(

2020-06-01 18:55 UTC, yurii-litvinov approved these changes
Окей, зачтена. Есть что улучшить, но уже достаточно хорошо, чтобы зачесть

2020-06-01 18:55 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +        protected class Node // LinkedList's element
А зачем он protected? :)

2020-06-01 18:55 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +        private Node shiftToCertainPosition(int position)
Методы ведь назывваются с заглавной :)

2020-06-01 18:55 UTC, yurii-litvinov commented on HW2/task1/Linkedlist.cs
> +            }
Ну а тут всё равно копипаст

2020-06-09 15:29 UTC, merged