Added homework 4 task 2 and tests for homework 4 task 2.
Diana-Govorova/SPbSU-SemesterII pull request #6
Opened 2020-04-14 19:11 UTC by Diana-Govorova

2020-04-17 10:35 UTC, yurii-litvinov requested changes
Не-а, этого недостаточно, всё ещё можно нарушить инвариант уникальности элементов в списке, через методы предка. И ещё нелишне бы поправить список по замечаниям к задаче 2.1

2020-06-09 15:28 UTC, yurii-litvinov requested changes
Комментарии к коммитам ужасающи

2020-06-09 15:28 UTC, yurii-litvinov commented on HW4/task2/UniqueList.cs
> +                throw new ItemAlreadyImplementedException($"Element {value} already exist.");
Не совсем. А если я зачем-то хочу выставить значение в данной позиции в такое же, как там и было? Например, list.Add(1, 0); list.SetElementOnPosition(1, 0);. Не хочу исключение в таком случае, потому что инвариант не нарушается.

2020-06-09 15:28 UTC, yurii-litvinov commented on HW4/task2/UniqueList.cs
> +        public override void DeleteValueByValue( T data)
Пробел лишний

2020-06-09 15:28 UTC, yurii-litvinov commented on HW4/task2/LinkedList.cs
> +        private Node shiftToCertainPosition(int position)
Методы именуются с заглавной

2020-07-14 17:50 UTC, yurii-litvinov requested changes

2020-07-14 17:50 UTC, yurii-litvinov commented on HW4/task2/LinkedList.cs
> +        protected Node head;
Не надо без нужды раскрывать своё состояние потомкам. Я бы сказал, что protecteed-полей вообще следует избегать.

2020-07-14 17:50 UTC, yurii-litvinov commented on HW4/task2/LinkedList.cs
> +            shiftToCertainPosition(position).Data = value;
Боюсь, что оно так не скомпилится, метод объявлен с заглавной, а вызывается со строчной

2020-07-14 17:50 UTC, yurii-litvinov commented on HW4/task2/UniqueList.cs
> +    public class UniqueList<T> : LinkedList<T>
Надо комментарий и к самому классу

2020-07-14 17:50 UTC, yurii-litvinov commented on HW4/task2/UniqueList.cs
> +            if (Contains(value) && (position != GetValuePositionByValue(value)))
Не проще ли здесь было this.GetNodeValueByPosition(position) != value?

2020-07-17 18:44 UTC, Diana-Govorova commented on HW4/task2/LinkedList.cs
> +        protected Node head;
Мне это нужно, чтобы в методе ShiftToCertainPosition возвращать элемент списка

2020-07-17 18:54 UTC, Diana-Govorova commented on HW4/task2/UniqueList.cs
> +            if (Contains(value) && (position != GetValuePositionByValue(value)))
Не разрешает сравнивать объекты типа T

2020-08-06 08:40 UTC, yurii-litvinov requested changes
Теперь всё хорошо, только CI не проходит. Почините?

2020-09-02 16:57 UTC, yurii-litvinov approved these changes

2020-10-15 20:47 UTC, merged